#!/usr/bin/python

import argparse
import os
import subprocess

def main():
    parser = argparse.ArgumentParser(description='Add scopes to scope sets')
    parser.add_argument('-c', required=True, help='command ("add" or "rm")')
    parser.add_argument('-s', required=True, help='shortcut')
    parser.add_argument('-u', required=True, help='user')
    args = parser.parse_args()

    # commands = ["add", "rm"]
    command = args.c

    shortcut = args.s
    user = args.u

    if command == "add":
        repo = os.getcwd()
        repo = repo.split('/')
        repo = repo[-1]

        url = "git@github.com:" + user + "/" + repo

        subprocess.check_call(["git", "remote", command, shortcut, url])
        subprocess.check_call(["git", "fetch", shortcut])
     else if command == "rm":
        subprocess.check_call(["git", "remote", shortcut])
     else:
	print "No vaid command given"

if __name__ == "__main__":
    main()
