#!/usr/bin/python

import argparse
import os
import subprocess

def main():
   parser = argparse.ArgumentParser(description='Add scopes to scope sets')
   parser.add_argument('-s', required=True, help='shortcut')
   parser.add_argument('-u', required=True, help='user')
   args = parser.parse_args()

   shortcut = args.s
   user = args.u
   repo = os.getcwd()
   repo = repo.split('/')
   repo = repo[-1]

   url = "git@github.com:" + user + "/" + repo

   subprocess.check_call(["git", "remote", "add", shortcut, url])
   subprocess.check_call(["git", "fetch", shortcut])

if __name__ == "__main__":
   main()
